#
# Makefile for the pedestal drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_PEDESTAL)	+= pedestal.o
obj-$(CONFIG_PEDESTAL)	+= rmt_ctrl.o
obj-$(CONFIG_PEDESTAL)	+= sound_box.o

